---
namespace: huaweidatacom
name: nce_fabric
# The version of the collection. Must be compatible with semantic versioning
version: 1.0.0
readme: README.md
authors:
description: Ansible Modules for HUAWEI iMaster NCE-Fabric Controller
license_file: 'LICENSE'
tags: 
- huaweidatacom
- NCE-Fabric
repository: https://github.com/HuaweiDatacomm/ac-ansible-module
documentation:
homepage: https://github.com/HuaweiDatacomm/ac-ansible-module
issues: https://github.com/HuaweiDatacomm/ac-ansible-module/issues