---
# ansible-playbook logicrouter_query.yml -e 'logicrouter_id="4ed05719-5c9a-4940-a03c-fc96be44c47c"'
# ansible-playbook logicrouter_query.yml -e 'logicrouter_id=""'

- name: Query LogicRouter
  hosts: localhost
  serial: True
  tasks:
    - name: Get token
      huaweidatacom.nce_fabric.nce_fabric_token:
        host: "{{ ac_host }}"
        port: "{{ ac_north_port }}"
        username: "{{ ac_user }}"
        password: "{{ ac_passwd }}"
      register: token
    - name: qeury logicrouters
      tags: qeury_logicrouters
      when: logicrouter_id == ''
      uri:
        url: 'https://{{ac_host}}:{{ac_north_port}}/controller/dc/v3/logicnetwork/routers'
        method: GET
        validate_certs: False
        return_content: yes
        headers:
          X-ACCESS-TOKEN: "{{token.token}}"
          Accept: application/json
          Content_Type: application/json
        status_code: 200
      register: logicrouters_result
      ignore_errors: yes
    - name: qeury logicrouter "{{logicrouter_id}}"
      tags: qeury_logicrouter
      when: logicrouter_id != ''
      uri:
        url: 'https://{{ac_host}}:{{ac_north_port}}/controller/dc/v3/logicnetwork/routers/router/{{logicrouter_id}}'
        method: GET
        validate_certs: False
        return_content: yes
        headers:
          X-ACCESS-TOKEN: "{{token.token}}"
          Accept: application/json
          Content_Type: application/json
        status_code: 200
      register: logicrouter_result
      ignore_errors: yes
    - name: response from get logicrouters
      when: logicrouter_id == ''
      debug:
        msg: "{{logicrouters_result.json.router}}"
    - name: response from query a logicrouter
      when: logicrouter_id != ''
      debug:
        msg: "{{logicrouter_result.json.router}}"
