---
# ansible-playbook logicrouter_delete.yml -e 'logicrouter_id="4ed05719-5c9a-4940-a03c-fc96be44c47c"'

- name: Delete LogicRouter
  hosts: localhost
  serial: True
  tasks:
    - name: Get token
      huaweidatacom.nce_fabric.nce_fabric_token:
        host: "{{ ac_host }}"
        port: "{{ ac_north_port }}"
        username: "{{ ac_user }}"
        password: "{{ ac_passwd }}"
      register: token
    - name: check logicrouter_id is null
      fail:
        msg: "Delete LogicRouter fail! logicrouter_id is null"
      when: logicrouter_id == ''
    - name: Delete logicrouter "{{logicrouter_id}}"
      tags: delete_logicrouter
      uri:
        url: 'https://{{ac_host}}:{{ac_north_port}}/controller/dc/v3/logicnetwork/routers/router/{{logicrouter_id}}'
        method: DELETE
        validate_certs: False
        return_content: yes
        headers:
          X-ACCESS-TOKEN: "{{token.token}}"
          Accept: application/json
          Content_Type: application/json
        status_code: 204
      register: logicrouter_result
      ignore_errors: yes
    - name: response from delete a logicrouter
      debug:
        msg: "{{logicrouter_result}}"
