---
# ansible-playbook logicrouter_update.yml -e 'logicrouter_id="4ed05719-5c9a-4940-a03c-fc96be44c47c" logicrouter_name="lroute1" logicrouter_desc="lroute1 update"'

- name: Update LogicRouter
  hosts: localhost
  serial: True
  tasks:
    - name: check logicrouter_id is null
      fail:
        msg: "Update LogicRouter fail! logicrouter_id is null"
      when: logicrouter_id == ''
    - name: check logicrouter_name is null
      fail:
        msg: "Update LogicRouter fail! logicrouter_name is null"
      when: logicrouter_name == ''
    - name: Get token
      huaweidatacom.nce_fabric.nce_fabric_token:
        host: "{{ ac_host }}"
        port: "{{ ac_north_port }}"
        username: "{{ ac_user }}"
        password: "{{ ac_passwd }}"
      register: token
    - name: Update logic router "{{logicrouter_id}}"
      tags: update_logicrouter
      vars:
        logicrouter_info:
          router:
            id: "{{logicrouter_id}}"
            name: "{{logicrouter_name}}"
            description: "{{logicrouter_desc}}"
      uri:
        url: 'https://{{ac_host}}:{{ac_north_port}}/controller/dc/v3/logicnetwork/routers/router/{{logicrouter_id}}'
        method: PUT
        body: '{{logicrouter_info}}'
        body_format: json
        validate_certs: False
        return_content: yes
        headers:
          X-ACCESS-TOKEN: "{{token.token}}"
          Accept: application/json
          Content_Type: application/json
        status_code: 200
      register: logicrouter_result
      ignore_errors: yes
    - name: response from update a logic router
      debug:
        msg: "{{logicrouter_result}}"
