---
# ansible-playbook tenant_query.yml -e 'tenant_id="3945d892-544f-4093-95f6-43aef6af0a26"'
# ansible-playbook tenant_query.yml -e 'tenant_id=""'

- name: Query Tenant
  hosts: localhost
  serial: True
  tasks:
    - name: Get token
      huaweidatacom.nce_fabric.nce_fabric_token:
        host: "{{ ac_host }}"
        port: "{{ ac_north_port }}"
        username: "{{ ac_user }}"
        password: "{{ ac_passwd }}"
      register: token
    - name: qeury tenants
      tags: qeury_tenants
      when: tenant_id == ''
      uri:
        url: 'https://{{ac_host}}:{{ac_north_port}}/controller/dc/v3/tenants'
        method: GET
        validate_certs: False
        return_content: yes
        headers:
          X-ACCESS-TOKEN: "{{token.token}}"
          Accept: application/json
          Content_Type: application/json
        status_code: 200
      register: tenants_result
      ignore_errors: yes
    - name: qeury tenant "{{tenant_id}}"
      tags: qeury_tenant
      when: tenant_id != ''
      uri:
        url: 'https://{{ac_host}}:{{ac_north_port}}/controller/dc/v3/tenants/tenant/{{tenant_id}}'
        method: GET
        validate_certs: False
        return_content: yes
        headers:
          X-ACCESS-TOKEN: "{{token.token}}"
          Accept: application/json
          Content_Type: application/json
        status_code: 200
      register: tenant_result
      ignore_errors: yes
    - name: response from get tenants
      when: tenant_id == ''
      debug:
        msg: "{{tenants_result.json.tenant}}"
    - name: response from query a tenant
      when: tenant_id != ''
      debug:
        msg: "{{tenant_result.json.tenant}}"
